# Generated by Django 4.2.4 on 2023-08-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('A', 'Adoption'), ('F', 'Fostering')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
