# Generated by Django 4.2.4 on 2023-08-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(upload_to='opportunities'),
        ),
    ]
